# Generated by Django 2.2.1 on 2019-06-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cp_id', models.AutoField(primary_key=True, serialize=False, verbose_name='회사정보 ID')),
                ('cp_name', models.CharField(max_length=200, verbose_name='회사, 단체명')),
                ('cp_present', models.CharField(max_length=100, verbose_name='대표자명')),
                ('cp_tel', models.CharField(max_length=45, verbose_name='전화번호')),
                ('cp_fax', models.CharField(max_length=45, verbose_name='팩스')),
                ('cp_county', models.IntegerField(verbose_name='도도부 현')),
                ('cp_city', models.CharField(max_length=100, verbose_name='도시')),
                ('cp_addr', models.CharField(max_length=200, verbose_name='주소')),
                ('cp_iduser', models.IntegerField(verbose_name='사용자 ID')),
                ('cp_regdate', models.DateField(verbose_name='등록일')),
                ('cp_updated', models.DateField(verbose_name='수정일')),
            ],
            options={
                'db_table': 'company',
                'managed': False,
            },
        ),
    ]
